import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import { randomBytes } from 'node:crypto';

const DEFAULT_TEMPLATE = `<?php
// Generated by CMS — do not edit by hand.
define('DB_NAME',     '{{DB_NAME}}');
define('DB_USER',     '{{DB_USER}}');
define('DB_PASSWORD', '{{DB_PASSWORD}}');
define('DB_HOST',     '{{DB_HOST}}');
define('DB_CHARSET',  'utf8mb4');
define('DB_COLLATE',  '');

define('AUTH_KEY',         '{{AUTH_KEY}}');
define('SECURE_AUTH_KEY',  '{{SECURE_AUTH_KEY}}');
define('LOGGED_IN_KEY',    '{{LOGGED_IN_KEY}}');
define('NONCE_KEY',        '{{NONCE_KEY}}');
define('AUTH_SALT',        '{{AUTH_SALT}}');
define('SECURE_AUTH_SALT', '{{SECURE_AUTH_SALT}}');
define('LOGGED_IN_SALT',   '{{LOGGED_IN_SALT}}');
define('NONCE_SALT',       '{{NONCE_SALT}}');

$table_prefix = '{{TABLE_PREFIX}}';

define('WP_HOME',    '{{PROTOCOL}}://{{DOMAIN}}');
define('WP_SITEURL', '{{PROTOCOL}}://{{DOMAIN}}');

define('DISALLOW_FILE_EDIT', true);
define('DISALLOW_FILE_MODS', true);

if ( ! defined( 'ABSPATH' ) ) define( 'ABSPATH', __DIR__ . '/' );
require_once ABSPATH . 'wp-settings.php';
`;

const SALT_KEYS = [
  'AUTH_KEY',
  'SECURE_AUTH_KEY',
  'LOGGED_IN_KEY',
  'NONCE_KEY',
  'AUTH_SALT',
  'SECURE_AUTH_SALT',
  'LOGGED_IN_SALT',
  'NONCE_SALT',
] as const;

export interface WpConfigVars {
  dbName: string;
  dbUser: string;
  dbPassword: string;
  dbHost: string;
  domain: string;
  tablePrefix?: string;
  /** Site URL scheme. Default 'https'; use 'http' when SSL is skipped. */
  protocol?: 'http' | 'https';
}

export interface WpConfigServiceOpts {
  /** Optional override template file. If absent, uses inline default. */
  templatePath?: string;
}

const newSalt = (): string => randomBytes(48).toString('base64');

export class WpConfigService {
  constructor(private readonly opts: WpConfigServiceOpts = {}) {}

  async generate(siteRoot: string, vars: WpConfigVars): Promise<{ configPath: string }> {
    let cfg = this.opts.templatePath
      ? await fs.readFile(this.opts.templatePath, 'utf8')
      : DEFAULT_TEMPLATE;

    const replacements: Record<string, string> = {
      DB_NAME: vars.dbName,
      DB_USER: vars.dbUser,
      DB_PASSWORD: vars.dbPassword,
      DB_HOST: vars.dbHost,
      DOMAIN: vars.domain,
      TABLE_PREFIX: vars.tablePrefix ?? 'wp_',
      PROTOCOL: vars.protocol ?? 'https',
    };
    for (const k of SALT_KEYS) replacements[k] = newSalt();

    for (const [k, v] of Object.entries(replacements)) {
      cfg = cfg.split(`{{${k}}}`).join(v);
    }

    const configPath = path.join(siteRoot, 'wp-config.php');
    const tmp = `${configPath}.tmp`;
    await fs.writeFile(tmp, cfg, { mode: 0o640 });
    await fs.rename(tmp, configPath);
    return { configPath };
  }
}
